spring:
  application:
    name: Customer-Feign-Hystrix-Order
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
feign:
  hystrix:
    enabled: true