server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
eureka:
    instance:
      prefer-ip-address: true #注册时使用服务的ip地址
      lease-expiration-duration-in-seconds: 60 #服务过期时间
      lease-renewal-interval-in-seconds: 30 #服务多长时间心跳一次
      instance-id: consumer-order-80
      #hostname: ${spring.cloud.client.ipAddress} #eureka实例
    client:
      service-url:
        defaultZone: http://localhost:7001/eureka/  #默认部署端口8761  Http://${eureka.instance.hostname:${server.port}/eureka/