server:
  port: 80
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
   # fetch-registry: false
    register-with-eureka: false
    #建立连接时间
    eureka-server-read-timeout-seconds: 5000
    #读取资源时间
    eureka-server-connect-timeout-seconds: 5000
spring:
  application:
    name: feign-text
  #feign日志以什么级别监控哪个接口
logging:
  level:
    com.yg.cloud.service.PaymentFeiginService: debug