server:
  port: 8005
spring:
  application:
    name: hystrix-payment
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: true
    fetch-registry: true